- openshift-release-info
It looks like https://openshift-release.svc.ci.openshift.org/graph?format=dot
is returning a 302 redirect. This follows the redirect.
> Fix openshift-release-info by following HTTP 302 redirects

- CI/run-kata-perf-suite
Resolves #17 in part.  This does not address the situation in which clusterbuster-results.json is removed, but it saves it after each job so that if the run gets interrupted it's up to date.
> Save clusterbuster-ci-results.json after each job

- clusterbuster
- examples/clusterbuster/classic
- examples/clusterbuster/files
- examples/clusterbuster/fio
- examples/clusterbuster/log
- examples/clusterbuster/memory
- examples/clusterbuster/pausepod
- lib/clusterbuster/CI/profiles/func_ci.profile
- lib/clusterbuster/CI/profiles/perf_ci.profile
- lib/clusterbuster/CI/profiles/release.profile
- lib/clusterbuster/CI/profiles/test_ci.profile
- lib/clusterbuster/CI/workloads/cpusoaker.workload
- lib/clusterbuster/CI/workloads/files.workload
- lib/clusterbuster/CI/workloads/fio.workload
- lib/clusterbuster/CI/workloads/uperf.workload
- lib/clusterbuster/libclusterbuster.sh
- lib/clusterbuster/workloads/classic.workload
- lib/clusterbuster/workloads/cpusoaker.workload
- lib/clusterbuster/workloads/files.workload
- lib/clusterbuster/workloads/fio.workload
- lib/clusterbuster/workloads/memory.workload
- lib/clusterbuster/workloads/server.workload
- lib/clusterbuster/workloads/simple.workload
- lib/clusterbuster/workloads/synctest.workload
- lib/clusterbuster/workloads/sysbench.workload
- lib/clusterbuster/workloads/uperf.workload
This is more efficient at creating pods, but it also thrashes nodes, so I may not be able to merge this.
> Use deployments rather than pods to spawn cpusoaker processes

- clusterbuster
- lib/clusterbuster/workloads/classic.workload
- lib/clusterbuster/workloads/cpusoaker.workload
- lib/clusterbuster/workloads/files.workload
- lib/clusterbuster/workloads/fio.workload
- lib/clusterbuster/workloads/memory.workload
- lib/clusterbuster/workloads/server.workload
- lib/clusterbuster/workloads/synctest.workload
- lib/clusterbuster/workloads/sysbench.workload
- lib/clusterbuster/workloads/uperf.workload
This should assist adding support for VMs.
Tested as follows:
```
$ cd examples/clusterbuster
$ for w in [a-z]* ; do echo $w; clusterbuster -f "$w" || break; done
$ for w in [a-z]* ; do echo $w; clusterbuster -f "$w" --deployment-type=rs || break; done
$ run-kata-perf-suite --force-abort --artifactdir=/var/tmp/d11 --profile=test_ci --no-cleanup --deployment-type=pod
$ run-kata-perf-suite --force-abort --artifactdir=/var/tmp/d11 --profile=test_ci --no-cleanup --deployment-type=rs
```
> Generalize how command line options are generated

- clusterbuster
- lib/clusterbuster/pod_files/classic.pl
- lib/clusterbuster/pod_files/client.pl
- lib/clusterbuster/pod_files/clientlib.pl
- lib/clusterbuster/pod_files/cpusoaker.pl
- lib/clusterbuster/pod_files/files.pl
- lib/clusterbuster/pod_files/fio.pl
- lib/clusterbuster/pod_files/logger.pl
- lib/clusterbuster/pod_files/memory.pl
- lib/clusterbuster/pod_files/server.pl
- lib/clusterbuster/pod_files/sync.pl
- lib/clusterbuster/pod_files/synctest.pl
- lib/clusterbuster/pod_files/sysbench.pl
- lib/clusterbuster/pod_files/uperf-client.pl
- lib/clusterbuster/pod_files/uperf-server.pl
If one process in a pod fails, the entire pod should be failed immediately rather than waiting forever (or until the job times out).
> Detect failure of multi-process pods and fail

- CI/run-kata-perf-suite
- clusterbuster
- Use oc/kubectl get -w to monitor pods for improved efficiency.
- Check for changes more frequently (every second vs. every 5 seconds)
because it doesn't put any more load on the apiserver.
> Improve efficiency of pod monitoring

- lib/clusterbuster/pod_files/fio.pl
- lib/clusterbuster/pod_files/uperf-client.pl
Workloads that run outside workers (currently fio and uperf) should check the status when their pipes are closed.
Tested selectively with fio and uperf runs.
> Check exit status of worker processes

- CI/run-kata-perf-suite
- clusterbuster
- lib/clusterbuster/libclusterbuster.sh
- lib/clusterbuster/workloads/sysbench.workload
- lib/clusterbuster/workloads/uperf.workload
- (run-kata-perf-suite) Don't acccept unused options not known to clusterbuster
- (clusterbuster) Fix up some missing/duplicate/incorrect help strings
- (libclusterbuster.sh) Move killall to libclusterbuster.sh
- (libclusterbuster.sh) Fix use of debug when debugging not enabled
- (all) Run shellcheck
> Miscellaneous fixes

- lib/clusterbuster/pod_files/sync.pl
Change to do_sync() implementation resulted in an extra token being passed which confused the timing code.
> Fix inadvertent timing error caused by change to sync API

- clusterbuster
Tested by changing the sleep(1) in the controller timestamp setup to usleep(1).  Without this fix, any run fails reliably.  With this fix, no failures.
> Fix race condition in initial timestamp handshake

- clusterbuster
Don't clean up by default if there is an error; use --cleanup-always to clean up even if something does go wrong.
> Add --cleanup-always option

- clusterbuster
- lib/clusterbuster/pod_files/classic.pl
- lib/clusterbuster/pod_files/client.pl
- lib/clusterbuster/pod_files/cpusoaker.pl
- lib/clusterbuster/pod_files/memory.pl
- lib/clusterbuster/pod_files/sync.pl
- lib/clusterbuster/pod_files/synctest.pl
- lib/clusterbuster/pod_files/sysbench.pl
- lib/clusterbuster/workloads/classic.workload
- lib/clusterbuster/workloads/cpusoaker.workload
- lib/clusterbuster/workloads/files.workload
- lib/clusterbuster/workloads/memory.workload
- lib/clusterbuster/workloads/synctest.workload
- lib/clusterbuster/workloads/sysbench.workload
- Simplifies startup logic
- Reduces the overhead of initial time synchronization
- Allows time synchronization to happen earlier in startup, and hence allows more accurate startup timing
> Do one initial sync per container rather than per process.

- lib/clusterbuster/pod_files/clientlib.pl
- lib/clusterbuster/pod_files/uperf-client.pl
If DNS behaves erratically on startup, an initial resolution may succeed but a later one fail.  This caused failures with uperf in CI.
> Workaround for any erratic DNS behavior

- analyze-clusterbuster-report
- clusterbuster-report
- lib/clusterbuster/analysis/ClusterBusterAnalysis.py
- lib/clusterbuster/analysis/spreadsheet/analyze_spreadsheet_generic.py
- lib/clusterbuster/analysis/spreadsheet/files_analysis.py
- lib/clusterbuster/analysis/summary/analyze_generic.py
- lib/clusterbuster/loader/ClusterBusterLoader.py
- lib/clusterbuster/loader/fio_loader.py
- Enable full analysis report for run split across multiple directories.
- Fix ratio generation
- Remove spurious debugging print
- More straightforwardly display options for report formats
> Clusterbuster analysis: handle output spread across multiple directories

- clusterbuster-report
- lib/clusterbuster/reporter/ClusterBusterReporter.py
Also, display a traceback if something goes wrong in reporting.
> - Don't unconditionally overwrite summary variables, which produces the wrong result for timelines.

- clusterbuster
Previously we had to watch out for leftover pods, because they could share uuid's with current pods. With a distinct xuuid for each run, we do not need that check.
> Fail if any pods error out very early.

- clusterbuster
Need to have affinity between worker pods and their drop cache counterparts.  This was broken in 8e905e62.
> Fix affinity between drop cache and fio/files workloads

- lib/clusterbuster/reporter/ClusterBusterReporter.py
If the numbers are very close in magnitude, it's likely an arithmetic rounding error.  If not, emit a warning.
> Protect against square root of negative number

- lib/clusterbuster/workloads/files.workload
- lib/clusterbuster/workloads/fio.workload
- lib/clusterbuster/workloads/memory.workload
- lib/clusterbuster/workloads/server.workload
- lib/clusterbuster/workloads/simple.workload
- lib/clusterbuster/workloads/synctest.workload
- lib/clusterbuster/workloads/sysbench.workload
- lib/clusterbuster/workloads/uperf.workload
The workload unknown argument checking doesn't work very well if the same arguments are passed to every job (as the CI script does).  Until there's a better fix, simply print a notice about the unknown arguments.
> Suppress workload unknown argument checking for now.

- clusterbuster
The default node class was set to empty; it should be client.
> Use client as the default node class, as opposed to empty.

- clusterbuster
Clusterbuster should fail if the reporting fails even if the run proper succeeds.
Fixes #67
> BUGFIX Correctly fail if the reporting step fails (#67)

- clusterbuster
- examples/clusterbuster/cpusoaker-perl
- lib/clusterbuster/pod_files/clusterbuster_pod_client.py
- lib/clusterbuster/pod_files/sync.py
- lib/clusterbuster/workloads/classic.workload
- lib/clusterbuster/workloads/cpusoaker.workload
- lib/clusterbuster/workloads/files.workload
- lib/clusterbuster/workloads/fio.workload
- lib/clusterbuster/workloads/logger.workload
- lib/clusterbuster/workloads/memory.workload
- lib/clusterbuster/workloads/server.workload
- lib/clusterbuster/workloads/synctest.workload
- lib/clusterbuster/workloads/sysbench.workload
- lib/clusterbuster/workloads/uperf.workload
There is no need for an explicit sync count; it just adds complexity.  The first sync step is always time synchronization; all commands after that are sync commands, except that the final command is rslt.  Any fail commands are always handled immediately.
> Clusterbuster: Eliminate requirement for explicit sync count

- clusterbuster
- lib/clusterbuster/libclusterbuster.sh
- Ensure that all kubectl/oc calls are debug tagged
- Clean up some explicit 'oc' calls
> - Add --dont-remove-namespaces option to preserve namespaces while cleaning up everything else

- clusterbuster
- lib/clusterbuster/workloads/files.workload
- lib/clusterbuster/workloads/fio.workload
- lib/clusterbuster/workloads/server.workload
- lib/clusterbuster/workloads/uperf.workload
- Reduce privilege requirements to the extent practicable
- Create namespaces with correct security policy declarations
This will not be sufficient for everything when the default policy becomes restricted.
> Kubernetes 1.22/OpenShift 4.11 security policy compatibility

- lib/clusterbuster/workloads/uperf.workload
Did not fix the case of using a secondary interface with uperf.
> Fix security policy  oversight for uperf with specified interface

- clusterbuster
Security context was at the wrong place, causing pod creation to fail quietly.
> Fix security constraints for replicasets

- set-worker-parameters
- Correct count of worker nodes (always use machineconfigpool as the source of truth)
- Correct -f argument
- Correct behavior if mcp is in the proccess of updating
- Wait for mcp to start updating before waiting for completion
> Fixes to set-worker-parameters

- ocp4-upi-util
- Allow Kata installation to a subset of nodes by label.
- Don't require a configuration file for commands that don't intrinsically need one (kata/cnv install).
> Allow installing Kata to a subset of nodes

- examples/clusterbuster/memory
- lib/clusterbuster/workloads/server.workload
- Fix memory example size so it doesn't blow out default Kata pod size
- Fix server workload reporting
> Minor fixes

- CI/run-kata-perf-suite
- clusterbuster
- lib/clusterbuster/CI/profiles/release.profile
- lib/clusterbuster/CI/workloads/cpusoaker.workload
- lib/clusterbuster/pod_files/sync.py
- lib/clusterbuster/reporting/analysis/spreadsheet/cpusoaker_analysis.py
- prom-extract
* Try to prevent excessively long lines of JSON output, which the shell can't handle.
* Allow specifying architecture and container image.  Architecture defaults to that of the run host, but can be changed.
* Sync pod tolerates running on infra node
* Correctly handle only a single available pin node
* run-kata-perf-suite should not use infra nodes as automatic pin nodes
* prom-extract sail more gracefully if any imports are missing (print an empty dictionary, so clusterbuster handles it correctly)
* Only wait for processes we care about, so we don't get into a deadlock with the stderr tee process.
* (minor feature) Add cpusoaker-initial-replicas to allow running a set of fixed replica count runs before starting with increments.
* Add 1, 2, 3, 4 as fixed replica counts to the release …
> Ci miscellaneous fixes

- clusterbuster
- lib/clusterbuster/libclusterbuster.sh
- By default, collect 50 logs in parallel
- By default, only collect logs in case of failure, except always collect the sync pod's logs
> Improve collection of pod logs

- clusterbuster
- oinst
- prom-extract
- Improve robustness of prom-extract by checking for openshift_client vs. just openshift (both provide modules named openshift).  Also, if something goes wrong during import, print an actionable diagnostic.
- Clean up stray environment exports from oinst.
- Don't attempt to prompt during installation if oinst is not connected to a tty.
- Protect clusterbuster from editing by running a transient copy of the script (same method as oinst).
> Miscellaneous small fixes

- clusterbuster
- Collect oc describe output from pods that fail.
- Add --force-no-metrics to not attempt to touch the prometheus pod at all
- Add variable timeout for pod startup (default 1 minute as before)
- Fix the startup message code
> Miscellaneous minor updates 2023-02-20

- clusterbuster
If the sync pod fails to start, e. g. because it's pinned to a nonexistent node, it should time out like any other pod.
> Time out if sync pod does not start

- clusterbuster
- lib/clusterbuster/workloads/files.workload
- lib/clusterbuster/workloads/fio.workload
- Containers need the security constraint, not pods or replicasets/deployments.  Applying a security constraint to a bare pod works, but not a higher level construct.  It's really just containers that need it.
- Add privileged serviceaccount to namespaces for OpenShift privileged pod handling.  Prior to OpenShift requiring this for privileged pods, any privileged pods will emit a warning about violation of PodSecurity.
- Add --privileged command line argument to force privileged pods
- Remove privilege from sync pod by default
- Handle cache dropping inside clusterbuster rather than the workloads. Workloads just say they need it; clusterbuster takes care of the details.
Other small fixes:
- Trivial fix for unspecified runtimeclass
- Log the pod monitor
> Fix privileged pod handling

- clusterbuster
Kata perf CI should use a specified image rather than simply using latest.
> CI release should use tied container image.

- CI/run-kata-perf-suite
The rlk debugging theorem: the amount of time required to find a typo is inversely proportional to the number of characters in error.
> Fix the analyze-clusterbuster-report command line

- lib/clusterbuster/reporting/analysis/spreadsheet/uperf_analysis.py
Networking conventionally is reported in bits/sec rather than bytes/sec.
> Report Mbits/sec rather than MBytes/sec for networking in spreadsheet analysis

- lib/clusterbuster/CI/workloads/cpusoaker.workload
Fixes regression from 1.1-ci.  This is needed to ensure that memory measurements from a prior kata run don't result in false results for the next runc run.
For example: if the previous run was kata with 180 pods, the amount of memory would be about 350 MB/pod, or 63 GB in all.  If we immediately start running the next runc run at 200 pods, the first metric interval will likely still reflect that 63 GB, even though the actual consumption of the runc pods will be more like 10 MB/pod (2 GB total).  This will result in false memory numbers for the runc run.
If we run all of the runc runs first followed by all of the kata runs, this won't be an issue; the worst that will happen is that the first metric reading of the runc-180 pod run will overlap with the start of the runc-200 pod run, so the …
> Run cpusoaker with runtimeclasses in the outer loop.

- monitor-cluster-resources
- Use oc get in a loop rather than oc get -w.  Unfortunately, watch doesn't capture most pods that terminate.
- Allow specifying nodes to monitor
- Legibility fixes
- Fix some corner cases resulting in Python errors
- Handle multi-container pods correctly
> Miscellaneous improvements

- clusterbuster
- Apply affinity rules to VMs in addition to pods.
- Allow VMs to be defined to be migrated if evicted.
- Fix cleanup sequence to remove the tempdir last.
- Allow run to wait forever even if sync pod is destroyed.
- Don't attemt to create a serviceaccount that already exists.
- Be more careful about cleanup; don't try to remove VMs if we aren't using them (if the virt operator isn't loaded, it will fail).
- Set the privileges correctly on namespaces that already exist.
> Miscellaneous fixes:

- CI/run-kata-perf-suite
- clusterbuster
- lib/clusterbuster/libclusterbuster.sh
- lib/clusterbuster/workloads/server.workload
- monitor-cluster-resources
- [clusterbuster] Fix sync service for separate sync namespace (broken in #134).
- [clusterbuster] Allow specifying node selectors with value, not just presence.
- [clusterbuster] Correctly use node selector for affinity if no explicit affinity is requested.
- [clusterbuster] Apply affinity specifications to VMs.
- [clusterbuster] Don't apply affinity specifications other than pin nodes to sync pod.
- [clusterbuster] Clean up both sync and "real" namespaces (broken in #134).
- [clusterbuster] Default no affinity or anti-affinity with sync pod.
- [clusterbuster] Ignore duplicate resource specifications (use only the last one from the command line).
- [clusterbuster] Fix shellcheck issues.
- [clusterbuster] Note that oc/kubectl commands are skipped with -n
- [clusterbuster] Fix redirection …
> Fixes and improvements:

- examples/ocp4-upi-util/config
- ocp4-upi-util
- Allow specifying different disk names for each node.
- Add an additional fallback location for pre-release builds.
- Clean up old binaries linked from /var/www/html/ocp4-upi.
- Fix cleanup of old host entries
- Update example
> Multiple fixes to UPI installer

- clusterbuster
- lib/clusterbuster/reporting/analysis/ClusterBusterAnalysis.py
- lib/clusterbuster/reporting/analysis/ci/analyze_postprocess.py
- lib/clusterbuster/reporting/analysis/spreadsheet/analyze_postprocess.py
- lib/clusterbuster/reporting/analysis/summary/analyze_postprocess.py
- lib/clusterbuster/reporting/loader/ClusterBusterLoader.py
The Kata Containers version is if anything more important than the Kata operator version.  Unfortunately, kata-version is already used for the operator version, so for compatibility the new item is called kata-containers-version.
Also fix a bug in the monitoring that resulted in the sync pod not being watched correctly.
> Fetch Kata version, not just Kata operator version

- clusterbuster
The termination sequence is very complex, due to the many asynchronous parts involved and the lack of IPC within bash.  For this, make sure that we allow the artifact collection to finish before exiting.
> Fix termination logic and collect all artifacts

- monitor-cluster-resources
- -O/--once: run only once rather than loop
- -A/--absolute: print absolute resource quantities
- --only-matches: record data only for matching pods
- --no-summary: don't print summary output
- --no-headers: don't print any header
> Miscellaneous new options targeting data collection

- clusterbuster
Retrieve logs and descriptions when clusterbuster run fails or times out.
> Retrieve artifacts if the run fails or times out

- CI/run-kata-perf-suite
- clusterbuster
- force-pull-clusterbuster-image
- lib/clusterbuster/container-image/Dockerfile
- lib/clusterbuster/container-image/Dockerfile.workloads
- lib/clusterbuster/container-image/Makefile
- lib/clusterbuster/workloads/fio.workload
- lib/clusterbuster/workloads/sysbench.workload
- lib/clusterbuster/workloads/uperf.workload
- Create multi-arch images correctly rather than having separate named images.
- Install procps-ng to get the ps command.
> Create multi-arch images

- docs/clusterbuster.md
- lib/clusterbuster/pod_files/clusterbuster_pod_client.py
This will not work correctly for deployments or replicasets, where the podnames have random hashes appended, so those deployment types should not be used where deterministic IDs are required.
Also make child_idx private; the index is passed to each subprocess so it is not necessary that clients have direct access to this member.
> Enable use _idname() as a deterministic random seed by using child index rather than process ID.

- clusterbuster
- lib/clusterbuster/workloads/fio.workload
- lib/clusterbuster/workloads/sysbench.workload
- lib/clusterbuster/workloads/uperf.workload
The main image was fixed early in the history of the kata-v1.2 branch.  This broke when I deleted the :<arch>-latest tags from the quay.io/rkrawitz/clusterbuster-workloads image.  The CI had inadvertently been using the mainline image.
> Fix the name of the workloads container image

- clusterbuster
- lib/clusterbuster/workloads/fio.workload
- prom-extract
With an example long run with high frequency metrics collection, this reduced the report size by about 75% (83 MB vs. 340 MB).
> Compact the clusterbuster report output by reducing indentation

- lib/clusterbuster/pod_files/fio.py
- lib/clusterbuster/reporting/reporter/fio_reporter.py
- Filter out messages printed on stdout (which fio appears to do)
- Report errors rather than simply fail JSON parsing
- Reporter catches missing data
> Improve error checking for fio

- clusterbuster
- clusterbuster-report
- lib/clusterbuster/pod_files/memory.py
- lib/clusterbuster/reporting/prettyprint.py
- lib/clusterbuster/reporting/reporter/ClusterBusterReporter.py
- lib/clusterbuster/reporting/reporter/cpusoaker_reporter.py
- lib/clusterbuster/reporting/reporter/files_reporter.py
- lib/clusterbuster/reporting/reporter/fio_reporter.py
- lib/clusterbuster/reporting/reporter/generic_nodata_reporter.py
- lib/clusterbuster/reporting/reporter/generic_reporter.py
- lib/clusterbuster/reporting/reporter/memory_reporter.py
- lib/clusterbuster/reporting/reporter/metrics/PrometheusMetrics.py
- lib/clusterbuster/reporting/reporter/server_reporter.py
- lib/clusterbuster/reporting/reporter/sysbench_reporter.py
- lib/clusterbuster/reporting/reporter/uperf_reporter.py
- lib/clusterbuster/workloads/memory.workload
* Add memory in use metric, and average metrics, to summary report.
* Only look at metrics captured during the active part of a run.
* Extend the prometheus snapshot in time to fully capture the beginning and end of the run.
* Report an error if a reporter fails to load due to a syntax error.
* Simplify the timeline report from the memory reporter.
* Allow memory jobs to be run as either subprocesses or function calls.
* Sync immediately before releasing memory if sync requested.
* Allow additional options for individual reporters.
* Add --metrics-interval option.
* Add --report-format as alias for -o for clusterbuster-report.
* Handle "oc version" correctly.
* Allow intervals other than 1 second for dense timeline.
* Clean up exception use in reporter to raise specific exceptions and …
> Add timeline support to memory reporter

- clusterbuster
- clusterbuster-report
- lib/clusterbuster/pod_files/memory.py
- lib/clusterbuster/reporting/prettyprint.py
- lib/clusterbuster/reporting/reporter/ClusterBusterReporter.py
- lib/clusterbuster/reporting/reporter/cpusoaker_reporter.py
- lib/clusterbuster/reporting/reporter/files_reporter.py
- lib/clusterbuster/reporting/reporter/fio_reporter.py
- lib/clusterbuster/reporting/reporter/generic_nodata_reporter.py
- lib/clusterbuster/reporting/reporter/generic_reporter.py
- lib/clusterbuster/reporting/reporter/memory_reporter.py
- lib/clusterbuster/reporting/reporter/metrics/PrometheusMetrics.py
- lib/clusterbuster/reporting/reporter/server_reporter.py
- lib/clusterbuster/reporting/reporter/sysbench_reporter.py
- lib/clusterbuster/reporting/reporter/uperf_reporter.py
- lib/clusterbuster/workloads/memory.workload
* Add memory in use metric, and average metrics, to summary report.
* Only look at metrics captured during the active part of a run.
* Extend the prometheus snapshot in time to fully capture the beginning and end of the run.
* Report an error if a reporter fails to load due to a syntax error.
* Simplify the timeline report from the memory reporter.
* Allow memory jobs to be run as either subprocesses or function calls.
* Sync immediately before releasing memory if sync requested.
* Allow additional options for individual reporters.
* Add --metrics-interval option.
* Add --report-format as alias for -o for clusterbuster-report.
* Handle "oc version" correctly.
* Allow intervals other than 1 second for dense timeline.
* Clean up exception use in reporter to raise specific exceptions and …
> Memory workload enhancements

- clusterbuster
- Work around issue where first `oc' command after cert rotation completes may fail.
- Timestamp messages from the sync monitor.
> Improve reliability of report collection from the sync controller

- lib/clusterbuster/reporting/reporter/fio_reporter.py
- lib/clusterbuster/reporting/reporter/sysbench_reporter.py
workloadOptions was renamed workload_options; there were still a few leftover old-style workloadOptions around.
Check for both so we can handle old reports.
> Clean up some leftover workloadOptions

- lib/clusterbuster/CI/workloads/uperf.workload
Use of either pin nodes or explicit anti-affinity will have the correct effect.
> Do not force affinity with the uperf ci workload

- clusterbuster
Need to use `%-<max_lineno_length>d` rather than %d.
> Align the column of the arguments by printing the line number with proper formatting

- CI/run-perf-ci-suite
- clusterbuster
- force-pull-clusterbuster-image
- lib/clusterbuster/CI/profiles/func_ci.profile
- lib/clusterbuster/CI/profiles/perf_ci.profile
- lib/clusterbuster/CI/profiles/release.profile
- lib/clusterbuster/CI/profiles/test_ci.profile
- Set the default start timeout to 180 seconds for VMs, as pulling the VM image can take much longer than the standard container image.
- Prefetch the VM image if a kubevirt object exists.
- All CI profiles should prefetch the images.
> Robustness improvements for VMs

- clusterbuster
- lib/clusterbuster/CI/workloads/files.workload
- lib/clusterbuster/pod_files/files.py
- lib/clusterbuster/pod_files/fio.py
- lib/clusterbuster/workloads/files.workload
- fio:
- fio prints some warnings on stdout rather than stderr, so we need to direct its output into a file.
- Re-raise errors correctly
- files:
- If emptydisk volume is specified for files workload, use it rather than /tmp.
> Fixes to fio and files workloads

- CI/run-perf-ci-suite
- README.md
- clusterbuster
- docs/clusterbuster.md
- lib/clusterbuster/CI/profiles/func_ci.profile
- lib/clusterbuster/CI/profiles/perf_ci.profile
- lib/clusterbuster/CI/profiles/release.profile
- lib/clusterbuster/CI/profiles/test_ci.profile
- lib/clusterbuster/CI/workloads/cpusoaker.workload
- lib/clusterbuster/CI/workloads/files.workload
- lib/clusterbuster/CI/workloads/fio.workload
- lib/clusterbuster/CI/workloads/uperf.workload
- lib/clusterbuster/libclusterbuster.sh
- lib/clusterbuster/pod_files/files.py
- lib/clusterbuster/pod_files/fio.py
- lib/clusterbuster/reporting/reporter/ClusterBusterReporter.py
- lib/clusterbuster/reporting/reporting_exceptions.py
- lib/clusterbuster/workloads/byo.workload
- lib/clusterbuster/workloads/cpusoaker.workload
- lib/clusterbuster/workloads/files.workload
- lib/clusterbuster/workloads/fio.workload
- prom-extract
- Eliminate --emptydirs and --emptydir (specify volumes explicitly)
- Fix option parsing for where there may be spaces in option values
- Allow specifying conditional workloads and runtimeclasses for run-perf-ci-suite
- Add pre-run and post-run script for run-perf-ci-suite
- Use volumes for files and fio
- Allow specifying auto volume size for files and fio
- Use /var/tmp/clusterbuster as the default work directory
- Correctly inject ssh keys into VM
- Generate a temporary ssh key if none provided with --ssh-keyfile
- Retrieve logs from VMs
- Rework the perf CI argument parsing logic to avoid having to change the clusterbuster arg parsing.
- Allow the stack trace to be used from all libclusterbuster.sh clients.
- Don't add a -N <inodes> argument to non-ext4 filesystems.
- Treat no …
> Improve support for volumes with VM workloads and rationalize the volume CLI

- clusterbuster
- Don't name check unnamed (emptydir/emptydisk) volumes
- Use --overwrite to label serviceaccount
> Minor bug fixes for storage validation and serviceaccount labeling

- clusterbuster
- lib/clusterbuster/CI/profiles/func_ci.profile
- lib/clusterbuster/CI/profiles/perf_ci.profile
- lib/clusterbuster/CI/profiles/release.profile
- lib/clusterbuster/CI/profiles/test_ci.profile
- Don't treat failure of a wait to indicate failure to retrieve logs; wait in bash sometimes fails seemingly due to jobs being prematurely reaped.  Instead look at the exit status of the oc logs/describe command.
- run-clusterbuster-2 needs to be inside a subshell due to the stderr redirection inside.
- Default storage for fio/files in CI profiles should be emptydisk; this will be overridden on the command line with the correct PVC if needed.
> Improve reliability of shutdown and error path:

- lib/clusterbuster/pod_files/cb_util.py
- lib/clusterbuster/pod_files/clusterbuster_pod_client.py
The startup attempts to determine the skew between the sync pod time and the worker pod time by determining the round trip time as seen by the worker (time to send request and receive reply) and the round trip time as seen remotely (time between receiving the request and servicing it).  The worker-side round trip time was calculated by taking the time stamp before and after the request to the sync pod.  That was being done incorrectly, because if the sync pod was not servicing requests when the initial request was made from the client, the time before the sync pod became responsive was considered part of the round trip time.  The fix is to not start that timer until a successful connection to the sync pod is made.
> Fix the timestamp calculation at worker startup

- CI/run-perf-ci-suite
- clusterbuster
- lib/clusterbuster/CI/workloads/cpusoaker.ci
- lib/clusterbuster/pod_files/files.py
- lib/clusterbuster/reporting/loader/ClusterBusterLoader.py
- lib/clusterbuster/reporting/reporter/ClusterBusterReporter.py
- prom-extract
- Eliminate duplicate reports
- Retrieve logs for VMs in addition to pods.
- Retrieve VM logs with correct (root) username.
- Handle Completed status in fail path.
- Add NFS PVCs.
- import sys at the top of prom-extract in case a later import fails (so we can report to stderr)
- Allow report types of parseable and parseable-python as aliases for the summary versions of both.
- Check status from io.close() in the files workload
- cpusoaker CI: handle runtimeclass correctly
- Reporting: break out some generic exceptions
- Correctly handle conditional non-workload options.
> Miscellaneous fixes/minor improvements:

- CI/run-perf-ci-suite
- clusterbuster
- lib/clusterbuster/CI/workloads/uperf.ci
- lib/clusterbuster/libclusterbuster.sh
- lib/clusterbuster/pod_files/clusterbuster_pod_client.py
- lib/clusterbuster/pod_files/sync.py
- lib/clusterbuster/reporting/analysis/spreadsheet/analyze_spreadsheet_generic.py
- lib/clusterbuster/reporting/analysis/spreadsheet/files_analysis.py
- lib/clusterbuster/workloads/byo.workload
- lib/clusterbuster/workloads/files.workload
- lib/clusterbuster/workloads/server.workload
- lib/clusterbuster/workloads/uperf.workload
- Retrieve qemu XML files from VMs
- Support multiple networks for VMs with multus (we have to do our own address assignment as CNV doesn't work with IPAM)
- Generate artifact directory names from timestamp to avoid inadvertently overwriting existing artifact directories.
- Retrieve all logs, not just from failing pods, in CI.
- Rename the stdout/stderr CI logs to reflect the change from kata to perf CI.
- Move the network interface options from uperf and server to top level to aid code reuse and simplify the logic.
- Change the reply from the sync to the workers to JSON so we can add more data to it if we need to.
- Ensure that all spreadsheet analysis is printed in numbers rather than suffixed human friendly.
- Files analysis should also analyze by direct vs. std IO.
> Miscellaneous (mostly VM) improvements 20240403

- CI/run-perf-ci-suite
- analyze-clusterbuster-report
- clusterbuster
- lib/clusterbuster/CI/profiles/func_ci.profile
- lib/clusterbuster/CI/profiles/perf_ci.profile
- lib/clusterbuster/CI/profiles/release.profile
- lib/clusterbuster/CI/profiles/test_ci.profile
- lib/clusterbuster/CI/workloads/fio.ci
- lib/clusterbuster/pod_files/clusterbuster_pod_client.py
- lib/clusterbuster/pod_files/files.py
- lib/clusterbuster/pod_files/fio.py
- lib/clusterbuster/reporting/analysis/ClusterBusterAnalysis.py
- lib/clusterbuster/reporting/analysis/ci/analyze_ci_generic.py
- lib/clusterbuster/reporting/analysis/ci/analyze_postprocess.py
- lib/clusterbuster/reporting/analysis/spreadsheet/cpusoaker_analysis.py
- lib/clusterbuster/reporting/analysis/spreadsheet/fio_analysis.py
- lib/clusterbuster/reporting/analysis/summary/analyze_generic.py
- lib/clusterbuster/reporting/analysis/summary/cpusoaker_analysis.py
- lib/clusterbuster/reporting/analysis/summary/files_analysis.py
- lib/clusterbuster/reporting/analysis/summary/fio_analysis.py
- lib/clusterbuster/reporting/loader/ClusterBusterLoader.py
- lib/clusterbuster/reporting/loader/cpusoaker_loader.py
- lib/clusterbuster/reporting/loader/files_loader.py
- lib/clusterbuster/reporting/loader/fio_loader.py
- lib/clusterbuster/reporting/loader/uperf_loader.py
- lib/clusterbuster/reporting/reporter/ClusterBusterReporter.py
- lib/clusterbuster/workloads/byo.workload
- lib/clusterbuster/workloads/files.workload
- lib/clusterbuster/workloads/fio.workload
- Clusterbuster:
- Use /var/opt/clusterbuster rather than /var/tmp/clusterbuster as work directory (including default mounted volumes).  This better comports with the Filesystem Hierarchy Standard and avoids apparent issues with selinux labeling on /var/tmp that gets inherited.
- Expand %r and %i in all uses of volume names (some, in particular volume mounts and VM mkfs, were previously missed).
- Report which invalid option triggered failure.
- Save the system and user configmaps in the artifacts directory.
- Try harder to clean up leftover storage for fio and files client (important when using a PVC for storage, since otherwise it doesn't get cleaned up)
- Set the desired containerdisk image for VMs.
- Perf CI suite:
- Allow repeated use of -n; -n -n runs clusterbuster with -n, so it's …
> Miscellaneous improvements/fixes:

- ocp4-upi-util
If KUBECONFIG is not set, ocp4-upi-util should just rely on the default assumed by OpenShift.
> ocp4-upi-util should not require KUBECONFIG to be set

- CI/run-perf-ci-suite
- analyze-clusterbuster-report
- clusterbuster
- clusterbuster-report
- lib/clusterbuster/CI/workloads/cpusoaker.ci
- lib/clusterbuster/CI/workloads/files.ci
- lib/clusterbuster/CI/workloads/fio.ci
- lib/clusterbuster/CI/workloads/uperf.ci
- lib/clusterbuster/libclusterbuster.sh
- lib/clusterbuster/pod_files/cb_util.py
- lib/clusterbuster/pod_files/clusterbuster_pod_client.py
- lib/clusterbuster/pod_files/fio.py
- lib/clusterbuster/pod_files/memory.py
- lib/clusterbuster/pod_files/sync.py
- lib/clusterbuster/reporting/reporter/ClusterBusterReporter.py
- lib/clusterbuster/reporting/reporter/memory_reporter.py
- lib/clusterbuster/workloads/uperf.workload
- ocp4-upi-util
Improve memory workload:
- Improve report from memory workload
- Generate page rate from active time only
- Fix memory operations rate calculation by using operation start time rather than allocation end time, which does not include the sync prior to operation start and hence is too early leading to too-low numbers.
- Report IOPS rate with summary
Other:
- Timestamp various messages from clusterbuster that weren't before.
- Don't warn about empty log from volumecontainerdisk container
- Rename _clean_numbers to _sanitize_json to better reflect purpose
- Fix most of the line too long flake8's
- Change get_start_and_end to non-static to allow it access to JSON data as a member
- Generate usable emergency report if run is aborted
- Allow more hyphen/underscore combinations with clusterbuster …
> Memory workload improvements and other minor fixes
