CI/run-kata-perf-suite
=> Add option to take prometheus snapshot to test suite

CI/run-kata-perf-suite, lib/clusterbuster/CI/workloads/cpusoaker.workload, lib/clusterbuster/CI/workloads/files.workload, lib/clusterbuster/CI/workloads/fio.workload, lib/clusterbuster/CI/workloads/uperf.workload
=> Use the runtimeclass as the innermost loop

CI/run-kata-perf-suite, clusterbuster
=> run-kata-perf-suite should accept other arguments

CI/run-kata-perf-suite, clusterbuster, lib/clusterbuster/analysis/ClusterBusterAnalysis.py, lib/clusterbuster/pod_files/files.pl, lib/clusterbuster/pod_files/fio.pl, lib/clusterbuster/workloads/classic.workload, lib/clusterbuster/workloads/cpusoaker.workload, lib/clusterbuster/workloads/files.workload, lib/clusterbuster/workloads/fio.workload, lib/clusterbuster/workloads/memory.workload, lib/clusterbuster/workloads/server.workload, lib/clusterbuster/workloads/simple.workload, lib/clusterbuster/workloads/synctest.workload, lib/clusterbuster/workloads/sysbench.workload, lib/clusterbuster/workloads/uperf.workload
Makes it easier to determine where in a prometheus snapshot something was running.
=> Allow use of a unique prefix for all objects

CI/run-kata-perf-suite, lib/clusterbuster/analysis/ClusterBusterAnalysis.py, lib/clusterbuster/analysis/spreadsheet/analyze_spreadsheet_generic.py, lib/clusterbuster/analysis/summary/analyze_generic.py, lib/clusterbuster/loader/ClusterBusterLoader.py, lib/clusterbuster/loader/fio_loader.py, lib/clusterbuster/pod_files/files.pl, lib/clusterbuster/pod_files/fio.pl, lib/clusterbuster/reporter/ClusterBusterReporter.py, lib/clusterbuster/workloads/files.workload, lib/clusterbuster/workloads/fio.workload
Don't error out hard if there is missing data in a report.
=> Report robustness

lib/clusterbuster/analysis/ClusterBusterAnalysis.py
=> Remove stray debugging messages

clusterbuster, lib/clusterbuster/CI/workloads/cpusoaker.workload, lib/clusterbuster/CI/workloads/files.workload, lib/clusterbuster/CI/workloads/fio.workload, lib/clusterbuster/CI/workloads/uperf.workload, lib/clusterbuster/libclusterbuster.sh, lib/clusterbuster/pod_files/server.pl, lib/clusterbuster/pod_files/sysbench.pl, lib/clusterbuster/pod_files/uperf-server.pl, lib/clusterbuster/workloads/classic.workload, lib/clusterbuster/workloads/cpusoaker.workload, lib/clusterbuster/workloads/files.workload, lib/clusterbuster/workloads/fio.workload, lib/clusterbuster/workloads/memory.workload, lib/clusterbuster/workloads/server.workload, lib/clusterbuster/workloads/simple.workload, lib/clusterbuster/workloads/synctest.workload, lib/clusterbuster/workloads/sysbench.workload, lib/clusterbuster/workloads/uperf.workload
- Standardize code for most of the workloads, preparatory to movingt out of the workload files.
- Add --force-abort to force an abort on any error.
=> Refactor the workloads to reduce the duplicated code.

clusterbuster, lib/clusterbuster/workloads/classic.workload, lib/clusterbuster/workloads/cpusoaker.workload, lib/clusterbuster/workloads/files.workload, lib/clusterbuster/workloads/fio.workload, lib/clusterbuster/workloads/memory.workload, lib/clusterbuster/workloads/server.workload, lib/clusterbuster/workloads/simple.workload, lib/clusterbuster/workloads/synctest.workload, lib/clusterbuster/workloads/sysbench.workload, lib/clusterbuster/workloads/uperf.workload
- Add inadvertent omission of final commit from refactor
- Change arglist construction
=> Tie up some loose ends from #27

clusterbuster, lib/clusterbuster/workloads/classic.workload, lib/clusterbuster/workloads/cpusoaker.workload, lib/clusterbuster/workloads/files.workload, lib/clusterbuster/workloads/fio.workload, lib/clusterbuster/workloads/memory.workload, lib/clusterbuster/workloads/server.workload, lib/clusterbuster/workloads/synctest.workload, lib/clusterbuster/workloads/sysbench.workload, lib/clusterbuster/workloads/uperf.workload
Reverts RobertKrawitz/OpenShift4-tools#30
=> Revert "Generalize how command line options are generated"

clusterbuster, lib/clusterbuster/libclusterbuster.sh
Adds the framework and options for kubectl/oc, API calls, and pod status updates.
=> Add debugging to clusterbuster

examples/clusterbuster/classic, examples/clusterbuster/files, examples/clusterbuster/fio, examples/clusterbuster/log, examples/clusterbuster/pausepod, examples/clusterbuster/server, examples/clusterbuster/synctest, examples/clusterbuster/sysbench, examples/clusterbuster/uperf, lib/clusterbuster/pod_files/classic.pl, lib/clusterbuster/pod_files/client.pl, lib/clusterbuster/pod_files/clientlib.pl, lib/clusterbuster/pod_files/cpusoaker.pl, lib/clusterbuster/pod_files/files.pl, lib/clusterbuster/pod_files/fio.pl, lib/clusterbuster/pod_files/logger.pl, lib/clusterbuster/pod_files/memory.pl, lib/clusterbuster/pod_files/server.pl, lib/clusterbuster/pod_files/sync.pl, lib/clusterbuster/pod_files/synctest.pl, lib/clusterbuster/pod_files/sysbench.pl, lib/clusterbuster/pod_files/uperf-client.pl, lib/clusterbuster/pod_files/uperf-server.pl, lib/clusterbuster/workloads/synctest.workload
A lot of code is duplicated between the pod workloads and can be cleaned up.
=> Factor out common code in the pod workloads

clusterbuster, lib/clusterbuster/pod_files/clientlib.pl, lib/clusterbuster/pod_files/cpusoaker.pl, lib/clusterbuster/pod_files/files.pl, lib/clusterbuster/pod_files/fio.pl, lib/clusterbuster/pod_files/logger.pl, lib/clusterbuster/pod_files/memory.pl, lib/clusterbuster/pod_files/sync.pl, lib/clusterbuster/reporter/ClusterBusterReporter.py, lib/clusterbuster/reporter/cpusoaker_reporter.py, lib/clusterbuster/reporter/files_reporter.py
- Clean up some of the reports.
- Use "my" rather than "our" in the perl files to localize variables
- Minor cleanup of object template code
=> Miscellaneous cleanup

lib/clusterbuster/pod_files/fio.pl, lib/clusterbuster/reporter/ClusterBusterReporter.py, lib/clusterbuster/reporter/fio_reporter.py, lib/clusterbuster/workloads/fio.workload
- Fix problem with tail recursion with reporting data
- Fix a few fio problems
=> Fix reporting

lib/clusterbuster/analysis/ClusterBusterAnalysis.py, lib/clusterbuster/analysis/spreadsheet/cpusoaker_analysis.py, lib/clusterbuster/reporter/ClusterBusterReporter.py
Also a few other trivial fixes.
=> Move _analyze_variables from generic to cpusoaker spreadsheet code

clusterbuster, docs/clusterbuster.md, lib/clusterbuster/pod_files/cb_util.py, lib/clusterbuster/pod_files/client.py, lib/clusterbuster/pod_files/clusterbuster_pod_client.py, lib/clusterbuster/pod_files/drop_cache.py, lib/clusterbuster/pod_files/files.py, lib/clusterbuster/pod_files/fio.py, lib/clusterbuster/pod_files/logger.py, lib/clusterbuster/pod_files/server.py, lib/clusterbuster/pod_files/sync.py, lib/clusterbuster/pod_files/sysbench.py, lib/clusterbuster/pod_files/uperf-server.py, lib/clusterbuster/workloads/server.workload, lib/clusterbuster/workloads/uperf.workload
- Add methods to retrieve network interfaces and IP addresses.
=> - Factor out utility methods common to controller and clients.

clusterbuster, lib/clusterbuster/CI/workloads/uperf.workload, lib/clusterbuster/pod_files/cb_util.py, lib/clusterbuster/pod_files/client.py, lib/clusterbuster/pod_files/clusterbuster_pod_client.py, lib/clusterbuster/pod_files/sync.py, lib/clusterbuster/pod_files/uperf-client.py, lib/clusterbuster/pod_files/uperf-server.py, lib/clusterbuster/workloads/server.workload, lib/clusterbuster/workloads/uperf.workload
Allow specification of explicit network interface to use for networking workloads.  This allows testing Multus.
Also, fix a bug in Uperf workload that would not run on non-headless services.
=> Explicit network interface support

clusterbuster, lib/clusterbuster/analysis/spreadsheet/cpusoaker_analysis.py, lib/clusterbuster/analysis/spreadsheet/files_analysis.py, lib/clusterbuster/analysis/summary/files_analysis.py, lib/clusterbuster/loader/ClusterBusterLoader.py, lib/clusterbuster/loader/uperf_loader.py
Allow running clusterbuster without collecting metrics.  Used if metrics not required or there is a problem with prometheus.
=> Enable running clusterbuster without metrics gathering

clusterbuster, lib/clusterbuster/workloads/server.workload, lib/clusterbuster/workloads/uperf.workload
Fix up everything so multus (at least for one additional network) works.
=> Add network annotation

clusterbuster
Don't blindly try to create a namespace or check for something in it -- test whether the namespace already exists.
=> Check for namespace existence before performing operations on it

lib/clusterbuster/analysis/spreadsheet/analyze_spreadsheet_generic.py, lib/clusterbuster/analysis/summary/cpusoaker_analysis.py, lib/clusterbuster/loader/ClusterBusterLoader.py
Analysis should run even if kata is not being tested.  This only gets past hard failures.
=> Eliminate analysis dependencies (phase 1)

lib/clusterbuster/workloads/server.workload, lib/clusterbuster/workloads/uperf.workload
Handle empty network interface provided to uperf and server.
=> Network interface fix

examples/clusterbuster/sysbench-cpu, examples/clusterbuster/sysbench-fileio, examples/clusterbuster/sysbench-memory, examples/clusterbuster/sysbench-mutex, examples/clusterbuster/sysbench-threads, lib/clusterbuster/pod_files/sysbench.py, lib/clusterbuster/reporter/ClusterBusterReporter.py, lib/clusterbuster/reporter/sysbench_reporter.py, lib/clusterbuster/workloads/sysbench.workload
Support cpu, memory, threads, and mutex workloads.
Also fix some reporting problems with fileio.
=> Support other non-database workloads in Sysbench

lib/clusterbuster/pod_files/files.py
The previous method did excessive file opens and in some cases did not work correctly (caused EINVAL in some of the mmap operations).
=> Clusterbuster: do direct I/O in the files module correctly

clusterbuster, lib/clusterbuster/CI/workloads/uperf.workload, lib/clusterbuster/workloads/server.workload, lib/clusterbuster/workloads/uperf.workload
Support configurations where multiple net-attach-defs must be used.
=> Allow use of multiple multus networks

clusterbuster
- Generate usable minimal JSON when a job fails.
- Always report even empty results.
=> Improve error reporting

lib/clusterbuster/pod_files/uperf-client.py
Simply report the error and move on.
=> Don't fail the entire run if one uperf case fails.

CI/run-kata-perf-suite, lib/clusterbuster/CI/workloads/cpusoaker.workload
- Fix getting the node list
- Handle Kata not installed
=> Minor fixes for node list and Kata not installed

oinst, share/OpenShift/installer/platforms/aws
Update from the most recent AWS list.
=> Update the AWS instance list

CI/run-kata-perf-suite, clusterbuster, lib/clusterbuster/CI/workloads/cpusoaker.workload, lib/clusterbuster/CI/workloads/uperf.workload
- Fix handling of explicit runc runtimeclass
- --uperf-annotate-vcpus to disable annotation altogether
=> Ci uperf annotation

lib/clusterbuster/reporting/analysis/spreadsheet/analyze_spreadsheet_generic.py
- Spreadsheets won't handle pretty numbers correctly
- Align ratios in the same column as values
=> - Spreadsheet analysis should not prettify numbers

CI/run-kata-perf-suite, clusterbuster
--force-cleanup-i-know-this-is-dangerous was inadvertently disabled.
=> Restore --force-cleanup-i-know-this-is-dangerous

clusterbuster
=> Fix typo in image name.

clusterbuster, lib/clusterbuster/workloads/files.workload, lib/clusterbuster/workloads/fio.workload
- Fix drop cache on fio and files
- Remove security context from drop cache pod (it only needs to be on the containers)
- Collect pod description from sync pod if it fails to start
=> Fix for privilege issues on fio and files

CI/run-kata-perf-suite
=> Separate out runtimeclasses in analysis report

README.md, monitor-cluster-resources
Real-time monitoring of Kubernetes/OpenShift cluster resource utilization for CPU, memory, and pods
=> Add monitor-cluster-resources command

ocp4-upi-util
Generalize the operator installation and allow migrating to infra nodes without requiring a config file.
=> Generalize operator installation

monitor-cluster-resources
Memory resource parsing was broken.
=> Fix parsing memory resources

clusterbuster, examples/clusterbuster/server, examples/clusterbuster/uperf, lib/clusterbuster/CI/workloads/uperf.workload
Also add --sync-in-first-namespace to allow placing the sync pod in the first workspace, so affinity will work correctly with that.
=> Add --sync-affinity to allow specifying affinity w/sync pod

monitor-cluster-resources
- -P pattern(s) of pods to list
- -R resource(s) to list
- -i interval between scans
- -c changed rows only (don't print rows with no changes)
- -t print relative timestamps
- -T print absolute timestamps (not mutually exclusive)
=> Enhancements and bug fixes for monitor-cluster-resources:

ocp4-upi-util
Also allow hyphens in command names and fix some shellcheck issues.
=> Add list-operators and describe-operator subcommands

lib/clusterbuster/pod_files/memory.py, lib/clusterbuster/workloads/memory.workload
Allow the memory workload to actively scan memory, to generate load.
=> Make memory workload active

ocp4-upi-util
=> More fixes to the architecture specification, and add option to not try to install dependencies

clusterbuster
Previous fix (in #142) was incomplete.
=> Complete monitor termination fix

monitor-cluster-resources
Also change formatting for the --once option to put nodes in rows.
=> Add --exact argument to not abbreviate output

README.md, net-traffic
=> Add net-traffic utility

ocp4-upi-util
- Default to masters schedulable only for no worker nodes.
- Rewrite the option parsing code.
- Clean up output for kata install
=> Cleanup for the UPI utility

clusterbuster
One "corner case" left over from previous fix.
=> Fix success case

lib/clusterbuster/pod_files/memory.py, lib/clusterbuster/workloads/memory.workload
- Fix the actual memory allocated by Python.  Allocating the whole bytearray at once results in the memory use temporarily being double the target use.
- Allow running the test in a loop, with a configurable interval between iterations.
=> Improvements to the memory workload

lib/clusterbuster/libclusterbuster.sh, lib/clusterbuster/pod_files/memory.py, lib/clusterbuster/workloads/memory.workload
Allow running random memory patterns to stress the memory system.
=> Allow randomizing options memory that make sense.

lib/clusterbuster/pod_files/memory.py, lib/clusterbuster/workloads/memory.workload
Intended for use with random workloads to allow overlapping operations.
=> Add option to not sync memory workload between iterations

clusterbuster, lib/clusterbuster/pod_files/clusterbuster_pod_client.py, lib/clusterbuster/pod_files/memory.py, lib/clusterbuster/reporting/reporter/ClusterBusterReporter.py, lib/clusterbuster/reporting/reporter/memory_reporter.py, lib/clusterbuster/workloads/memory.workload
- Allow more discrete randomization, by steps (e. g. memory by 1 MB or 1 GB)
- Add memory reporter with timeline
- Fix one place in that didn't correctly get the process index
- Export the report format to workload-specific reporters
=> More flexibility for the memory workload:

lib/clusterbuster/container-image/Dockerfile.base, lib/clusterbuster/container-image/Dockerfile.workloads, lib/clusterbuster/container-image/Makefile, lib/clusterbuster/container-image/firstboot.vm
This greatly improves a memory performance problem observed in VMs running Fedora. It's also closer in line with RHEL.
=> Switch image from Fedora base to CentOS Stream.

clusterbuster
Also report creation of secrets only if report object creation is enabled
=> Fix creation of namespaces (broken in #172)

lib/clusterbuster/pod_files/clusterbuster_pod_client.py, lib/clusterbuster/pod_files/fio.py, lib/clusterbuster/workloads/fio.workload, lib/clusterbuster/workloads/fio/generic.jobfile
* Don't run sync
* Run fio with --invalidate=0
=> --fio-drop-cache=0 should function as intended

clusterbuster, lib/clusterbuster/pod_files/sync.py
Allow optional sleep time between individual sub-jobs within a job.
=> Add --step-interval argument to allow for delay between steps

CI/run-perf-ci-suite, analyze-clusterbuster-report, clusterbuster, lib/clusterbuster/CI/workloads/cpusoaker.workload, lib/clusterbuster/CI/workloads/files.workload, lib/clusterbuster/CI/workloads/fio.workload, lib/clusterbuster/CI/workloads/uperf.workload, lib/clusterbuster/libclusterbuster.sh, lib/clusterbuster/metrics-default.yaml, lib/clusterbuster/pod_files/byo.py, lib/clusterbuster/pod_files/clusterbuster_pod_client.py, lib/clusterbuster/pod_files/fio.py, lib/clusterbuster/pod_files/sysbench.py, lib/clusterbuster/pod_files/uperf-client.py, lib/clusterbuster/reporting/analysis/ClusterBusterAnalysis.py, lib/clusterbuster/reporting/analysis/ci/analyze_postprocess.py, lib/clusterbuster/reporting/analysis/spreadsheet/analyze_postprocess.py, lib/clusterbuster/reporting/analysis/summary/analyze_postprocess.py, lib/clusterbuster/reporting/loader/ClusterBusterLoader.py, lib/clusterbuster/reporting/reporter/ClusterBusterReporter.py, lib/clusterbuster/workloads/cpusoaker.workload, lib/clusterbuster/workloads/fio.workload, lib/clusterbuster/workloads/logger.workload, lib/clusterbuster/workloads/memory.workload
Also fix a number of loading issue found in the process of testing.
=> Treat VM as a runtimeclass to simplify use in CI

lib/clusterbuster/pod_files/cb_util.py
Container pid1 acts as local init, so it needs to wait() in a loop
to catch any exiting processes so zombies don't build up.
=> Container PID 1 needs to perform init(8) functionality

clusterbuster
Dedicated I/O thread for a PVC mounted in a VM can improve performance.
=> Add dedicated I/O thread option for PVCs

lib/clusterbuster/pod_files/waitforever.py, lib/clusterbuster/workloads/waitforever.workload
Purpose is to create a container/VM that allows running something else externally in it.
=> Add waitforever workload.

lib/clusterbuster/pod_files/cb_util.py, lib/clusterbuster/pod_files/waitforever.py, lib/clusterbuster/reporting/reporter/memory_reporter.py
- Silence no child processes error from pid 1.
- Remove inadvertent debug print from memory reporter
=> Minor fixes

CI/run-perf-ci-suite, clusterbuster, clusterbuster-report, lib/clusterbuster/libclusterbuster.sh, lib/clusterbuster/reporting/loader/ClusterBusterLoader.py, lib/clusterbuster/reporting/reporter/ClusterBusterReporter.py
Add -z option to compress report to clusterbuster, run-perf-ci-suite, and the reporter/loader
=> Save space with optional compressed clusterbuster report
